In [1]:
import pandas as pd
import numpy as np

In [2]:
# 设置dataframe的行列输出数
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

# 问题 1 

## 构建DataFrame：**Energy**

1. 从`Energy Indicators.xls`加载数据到名为**Energy**的DataFrame。要求如下：
   - 跳过不需要的footer和header，前两列是不需要的数据
   - 列名应处理并保留为：['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
   

2. 数据转化
   - 将`Energy Supply`转化为gigajoules（1 petajoule = 1,000,000 gigajoules）
   - 将所有数值为“...”的，转化为np.NaN数据类型
   - 将部分国家名按照如下的dict做替换<br>
       ```"Republic of Korea": "South Korea",
       "United States of America": "United States",
       "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
       "China, Hong Kong Special Administrative Region": "Hong Kong"```
   - 去掉国家名中含有的数字，例如：`'Switzerland17'` 应该为 `'Switzerland'`；找到类似的全部国家名并处理
   - 去掉国家名中括号以及括号内包含的部分，例如：`'Bolivia (Plurinational State of)'` 应该为 `'Bolivia'`；找到类似的全部国家名并处理

## 构建DataFrame：**GDP**

1. 从`world_bank.csv`加载数据到名为**GDP**的Dataframe。要求如下：
    - 将部分国家名按照如下的dict做替换<br>
        ```"Korea, Rep.": "South Korea", 
        "Iran, Islamic Rep.": "Iran",
        "Hong Kong SAR, China": "Hong Kong"```

## 构建DataFrame：**ScimEn**

1. 从`scimagojr-3.xlsx`加载数据到名为**ScimEn**的Dataframe。


## 连接以上3个DataFrame

使用国家名称连接以上3个DataFrame形成一个新的数据集。其中GDP数据中仅使用最后10年的数据（2006-2015），且只要Rank值1-15的国家。 新的DataFrame最后的要求如下：
- Index为国家名
- 列名为：['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
- 最后这个DataFrame应为（15，20）的shape

## 定义一个Funtion，最后Return这个DataFrame

In [3]:
# 1.1
# 1.1.1
Energy=pd.read_excel('Energy Indicators.xls',skiprows=16,skipfooter=38)
Energy

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Energy Supply,Energy Supply per capita,Renewable Electricity Production
0,NaN,NaN,NaN,Petajoules,Gigajoules,%
1,NaN,Afghanistan,Afghanistan,321,10,78.6693
2,NaN,Albania,Albania,102,35,100
3,NaN,Algeria,Algeria,1959,51,0.55101
4,NaN,American Samoa,American Samoa,...,...,0.641026
5,NaN,Andorra,Andorra,9,121,88.6957
6,NaN,Angola,Angola,642,27,70.9091
7,NaN,Anguilla,Anguilla,2,136,0
8,NaN,Antigua and Barbuda,Antigua and Barbuda,8,84,0
9,NaN,Argentina,Argentina,3378,79,24.0645
10,NaN,Armenia,Armenia,143,48,28.2361
11,NaN,Aruba,Aruba,12,120,14.8707
12,NaN,Australia,Australia1,5386,231,11.8108
13,NaN,Austria,Austria,1391,164,72.4528
14,NaN,Azerbaijan,Azerbaijan,567,60,6.38434
15,NaN,Bahamas,Bahamas,45,118,0
16,NaN,Bahrain,Bahrain,574,425,0
17,NaN,Bangladesh,Bangladesh,1625,10,1.96633
18,NaN,Barbados,Barbados,19,69,0
19,NaN,Belarus,Belarus,1142,120,0.463389
20,NaN,Belgium,Belgium,2338,210,9.95974
21,NaN,Belize,Belize,13,39,64.69
22,NaN,Benin,Benin,170,16,0
23,NaN,Bermuda,Bermuda,6,88,0
24,NaN,Bhutan,Bhutan,63,83,100
25,NaN,Bolivia (Plurinational State of),Bolivia (Plurinational State of),336,32,31.4771
26,NaN,"Bonaire, Sint Eustatius and Saba","Bonaire, Sint Eustatius and Saba",5,213,0
27,NaN,Bosnia and Herzegovina,Bosnia and Herzegovina,266,70,41.4647
28,NaN,Botswana,Botswana,86,39,0.131406
29,NaN,Brazil,Brazil,12149,59,69.648
30,NaN,British Virgin Islands,British Virgin Islands,2,85,0
31,NaN,Brunei Darussalam,Brunei Darussalam,127,310,0.045434
32,NaN,Bulgaria,Bulgaria,703,97,17.2346
33,NaN,Burkina Faso,Burkina Faso,164,10,14.5007
34,NaN,Burundi,Burundi,58,6,86.7925
35,NaN,Cabo Verde,Cabo Verde,7,15,21.2276
36,NaN,Cambodia,Cambodia,250,17,57.3116
37,NaN,Cameroon,Cameroon,307,14,70.8863
38,NaN,Canada,Canada,10431,296,61.9454
39,NaN,Cayman Islands,Cayman Islands,8,131,0
40,NaN,Central African Republic,Central African Republic,23,5,85.6354
41,NaN,Chad,Chad,77,6,0
42,NaN,Chile,Chile,1613,92,28.0066
43,NaN,China,China2,127191,93,19.7549
44,NaN,"China, Hong Kong Special Administrative Region","China, Hong Kong Special Administrative Region3",585,82,0
45,NaN,"China, Macao Special Administrative Region","China, Macao Special Administrative Region4",47,83,0
46,NaN,Colombia,Colombia,1513,32,63.0028
47,NaN,Comoros,Comoros,5,7,11.6279
48,NaN,Congo,Congo,102,23,57.7489
49,NaN,Cook Islands,Cook Islands,1,48,0
50,NaN,Costa Rica,Costa Rica,222,47,88.7364
51,NaN,Côte d'Ivoire,Côte d'Ivoire,547,25,22.8228
52,NaN,Croatia,Croatia,321,75,64.2841
53,NaN,Cuba,Cuba,585,51,0.663532
54,NaN,Curaçao,Curaçao,78,502,0
55,NaN,Cyprus,Cyprus,82,71,6.48019
56,NaN,Czech Republic,Czech Republic,1751,166,7.06713
57,NaN,Democratic People's Republic of Korea,Democratic People's Republic of Korea,612,25,70.1803
58,NaN,Democratic Republic of the Congo,Democratic Republic of the Congo,888,12,99.5943
59,NaN,Denmark,Denmark5,725,129,33.5377
60,NaN,Djibouti,Djibouti,11,13,0
61,NaN,Dominica,Dominica,2,28,36.6337
62,NaN,Dominican Republic,Dominican Republic,339,33,11.2506
63,NaN,Ecuador,Ecuador,680,43,47.7149
64,NaN,Egypt,Egypt,3422,39,8.80571
65,NaN,El Salvador,El Salvador,176,29,56.4451
66,NaN,Equatorial Guinea,Equatorial Guinea,73,91,6.36364
67,NaN,Eritrea,Eritrea,34,7,0.550964
68,NaN,Estonia,Estonia,258,195,4.18079
69,NaN,Ethiopia,Ethiopia,1394,15,99.9082
70,NaN,Faeroe Islands,Faeroe Islands,9,179,38.5665
71,NaN,Falkland Islands (Malvinas),Falkland Islands (Malvinas),1,258,33.3333
72,NaN,Fiji,Fiji,31,36,62.0047
73,NaN,Finland,Finland,1374,252,19.5366
74,NaN,France,France6,10597,166,17.0203
75,NaN,French Guiana,French Guiana,13,52,62.0047
76,NaN,French Polynesia,French Polynesia,12,44,26.8556
77,NaN,Gabon,Gabon,99,60,37.5
78,NaN,Gambia,Gambia,14,7,0
79,NaN,Georgia,Georgia,163,40,82.2249
80,NaN,Germany,Germany,13261,165,17.9015
81,NaN,Ghana,Ghana,316,12,63.1026
82,NaN,Gibraltar,Gibraltar,8,245,0
83,NaN,Greece,Greece,993,90,24.7953
84,NaN,Greenland,Greenland7,9,166,78.125
85,NaN,Grenada,Grenada,5,43,0
86,NaN,Guadeloupe,Guadeloupe,33,70,14.8148
87,NaN,Guam,Guam,...,...,0
88,NaN,Guatemala,Guatemala,452,29,49.5217
89,NaN,Guernsey,Guernsey,0,6,0
90,NaN,Guinea,Guinea,145,12,48.4422
91,NaN,Guinea-Bissau,Guinea-Bissau,29,17,0
92,NaN,Guyana,Guyana,34,45,0
93,NaN,Haiti,Haiti,172,16,12.7602
94,NaN,Honduras,Honduras,217,28,37.7632
95,NaN,Hungary,Hungary,947,95,3.26363
96,NaN,Iceland,Iceland,312,957,99.9724
97,NaN,India,India,33195,26,14.9691
98,NaN,Indonesia,Indonesia8,8754,35,12.189
99,NaN,Iran (Islamic Republic of),Iran (Islamic Republic of),9172,119,5.70772
100,NaN,Iraq,Iraq,2077,61,7.87155
101,NaN,Ireland,Ireland,548,117,20.9211
102,NaN,Isle of Man,Isle of Man,0,4,0.793651
103,NaN,Israel,Israel,997,128,0.872525
104,NaN,Italy,Italy9,6530,109,33.6672
105,NaN,Jamaica,Jamaica,108,39,5.6156
106,NaN,Japan,Japan10,18984,149,10.2328
107,NaN,Jersey,Jersey,3,34,0
108,NaN,Jordan,Jordan,325,45,0.335979
109,NaN,Kazakhstan,Kazakhstan,3548,208,8.11278
110,NaN,Kenya,Kenya,873,20,73.7571
111,NaN,Kiribati,Kiribati,1,8,0
112,NaN,Kuwait,Kuwait11,1475,410,0
113,NaN,Kyrgyzstan,Kyrgyzstan,167,29,93.4766
114,NaN,Lao People's Democratic Republic,Lao People's Democratic Republic,85,13,93.2901
115,NaN,Latvia,Latvia,183,91,48.8323
116,NaN,Lebanon,Lebanon,289,55,6.61048
117,NaN,Lesotho,Lesotho,48,23,100
118,NaN,Liberia,Liberia,83,19,0
119,NaN,Libya,Libya,707,113,0
120,NaN,Liechtenstein,Liechtenstein,3,79,96.4706
121,NaN,Lithuania,Lithuania,282,95,41.0332
122,NaN,Luxembourg,Luxembourg,168,307,45.5332
123,NaN,Madagascar,Madagascar,166,7,50.8156
124,NaN,Malawi,Malawi,101,6,89.1356
125,NaN,Malaysia,Malaysia,3417,116,7.75459
126,NaN,Maldives,Maldives,15,43,0
127,NaN,Mali,Mali,66,4,64.7682
128,NaN,Malta,Malta,31,75,1.4197
129,NaN,Marshall Islands,Marshall Islands,1,28,0
130,NaN,Martinique,Martinique,33,84,2.60771
131,NaN,Mauritania,Mauritania,51,13,0
132,NaN,Mauritius,Mauritius,58,46,3.53186
133,NaN,Mexico,Mexico,7944,64,12.9134
134,NaN,Micronesia (Federated States of),Micronesia (Federated States of),2,21,2.94118
135,NaN,Mongolia,Mongolia,475,166,0
136,NaN,Montenegro,Montenegro,42,67,65.5815
137,NaN,Montserrat,Montserrat,1,153,0
138,NaN,Morocco,Morocco,796,23,15.8918
139,NaN,Mozambique,Mozambique,469,18,94.6309
140,NaN,Myanmar,Myanmar,682,13,72.0421
141,NaN,Namibia,Namibia,63,27,95.7944
142,NaN,Nauru,Nauru,1,60,0
143,NaN,Nepal,Nepal,458,16,99.6805
144,NaN,Netherlands,Netherlands12,3199,190,6.32466
145,NaN,New Caledonia,New Caledonia,51,200,20.431
146,NaN,New Zealand,New Zealand,876,196,72.8731
147,NaN,Nicaragua,Nicaragua,149,25,40.7639
148,NaN,Niger,Niger,87,5,0
149,NaN,Nigeria,Nigeria,5589,32,18.3903
150,NaN,Niue,Niue,0,65,0
151,NaN,Northern Mariana Islands,Northern Mariana Islands,...,...,0
152,NaN,Norway,Norway,1388,273,97.6356
153,NaN,Oman,Oman,1015,260,0
154,NaN,Pakistan,Pakistan,2868,16,31.8768
155,NaN,Palau,Palau,3,152,18.75
156,NaN,Panama,Panama,158,42,57.5095
157,NaN,Papua New Guinea,Papua New Guinea,144,20,23.9464
158,NaN,Paraguay,Paraguay,228,35,99.995
159,NaN,Peru,Peru,858,28,51.9686
160,NaN,Philippines,Philippines,1781,18,26.1726
161,NaN,Poland,Poland,4121,107,5.5379
162,NaN,Portugal,Portugal13,899,86,53.3403
163,NaN,Puerto Rico,Puerto Rico,56,15,1.08081
164,NaN,Qatar,Qatar,1396,664,0
165,NaN,Republic of Korea,Republic of Korea,11007,221,2.27935
166,NaN,Republic of Moldova,Republic of Moldova,93,23,5.08287
167,NaN,Réunion,Réunion,59,70,28.2972
168,NaN,Romania,Romania,1339,68,34.3845
169,NaN,Russian Federation,Russian Federation,30709,214,17.2887
170,NaN,Rwanda,Rwanda,95,9,35.8353
171,NaN,Saint Helena,Saint Helena,0,40,9.09091
172,NaN,Saint Kitts and Nevis,Saint Kitts and Nevis,4,73,0
173,NaN,Saint Lucia,Saint Lucia,6,33,0
174,NaN,Saint Pierre and Miquelon,Saint Pierre and Miquelon,1,162,2.12766
175,NaN,Saint Vincent and the Grenadines,Saint Vincent and the Grenadines,3,28,16.6667
176,NaN,Samoa,Samoa,4,22,31.3559
177,NaN,Sao Tome and Principe,Sao Tome and Principe,3,14,10.4478
178,NaN,Saudi Arabia,Saudi Arabia14,7985,264,0.000352
179,NaN,Senegal,Senegal,154,11,1.99824
180,NaN,Serbia,Serbia15,618,69,27.2162
181,NaN,Seychelles,Seychelles,9,94,1.9774
182,NaN,Sierra Leone,Sierra Leone,67,11,64.0244
183,NaN,Singapore,Singapore,1120,207,0
184,NaN,Sint Maarten (Dutch part),Sint Maarten (Dutch part),12,327,0
185,NaN,Slovakia,Slovakia,711,131,20.2171
186,NaN,Slovenia,Slovenia,287,139,31.8642
187,NaN,Solomon Islands,Solomon Islands,6,11,0
188,NaN,Somalia,Somalia,126,12,0
189,NaN,South Africa,South Africa,6341,119,1.68702
190,NaN,South Sudan,South Sudan,28,2,0.423729
191,NaN,Spain,Spain16,4923,106,37.9686
192,NaN,Sri Lanka,Sri Lanka,388,19,59.5732
193,NaN,State of Palestine,State of Palestine,61,14,0
194,NaN,Sudan,Sudan,608,16,78.4105
195,NaN,Suriname,Suriname,34,65,22.0238
196,NaN,Swaziland,Swaziland,49,39,40.678
197,NaN,Sweden,Sweden,2044,212,46.5985
198,NaN,Switzerland,Switzerland17,1113,136,57.7455
199,NaN,Syrian Arab Republic,Syrian Arab Republic,542,28,11.5683
200,NaN,Tajikistan,Tajikistan,106,13,99.7429
201,NaN,Thailand,Thailand,5336,79,4.30519
202,NaN,The former Yugoslav Republic of Macedonia,The former Yugoslav Republic of Macedonia,117,56,26.1405
203,NaN,Timor-Leste,Timor-Leste,7,6,0
204,NaN,Togo,Togo,134,19,80.1802
205,NaN,Tonga,Tonga,3,28,0
206,NaN,Trinidad and Tobago,Trinidad and Tobago,824,611,0
207,NaN,Tunisia,Tunisia,430,39,3.49255
208,NaN,Turkey,Turkey,4897,64,28.5367
209,NaN,Turkmenistan,Turkmenistan,1102,210,0
210,NaN,Turks and Caicos Islands,Turks and Caicos Islands,3,85,0
211,NaN,Tuvalu,Tuvalu,...,...,0
212,NaN,Uganda,Uganda,452,12,68.0182
213,NaN,Ukraine,Ukraine18,4844,107,8.06731
214,NaN,United Arab Emirates,United Arab Emirates,2710,300,0
215,NaN,United Kingdom of Great Britain and Northern I...,United Kingdom of Great Britain and Northern I...,7920,124,10.6005
216,NaN,United Republic of Tanzania,United Republic of Tanzania,994,20,31.0728
217,NaN,United States of America,United States of America20,90838,286,11.571
218,NaN,United States Virgin Islands,United States Virgin Islands,...,...,0
219,NaN,Uruguay,Uruguay,196,58,71.605
220,NaN,Uzbekistan,Uzbekistan,1798,62,21.3284
221,NaN,Vanuatu,Vanuatu,3,10,14.7059
222,NaN,Venezuela (Bolivarian Republic of),Venezuela (Bolivarian Republic of),2871,95,67.8345
223,NaN,Viet Nam,Viet Nam,2554,28,45.3215
224,NaN,Wallis and Futuna Islands,Wallis and Futuna Islands,0,26,0
225,NaN,Yemen,Yemen,344,13,0
226,NaN,Zambia,Zambia,400,26,99.7147
227,NaN,Zimbabwe,Zimbabwe,480,32,52.5361

In [4]:
Energy=Energy.iloc[1:,2:]
Energy

,Unnamed: 2,Energy Supply,Energy Supply per capita,Renewable Electricity Production
1,Afghanistan,321,10,78.6693
2,Albania,102,35,100
3,Algeria,1959,51,0.55101
4,American Samoa,...,...,0.641026
5,Andorra,9,121,88.6957
6,Angola,642,27,70.9091
7,Anguilla,2,136,0
8,Antigua and Barbuda,8,84,0
9,Argentina,3378,79,24.0645
10,Armenia,143,48,28.2361
11,Aruba,12,120,14.8707
12,Australia1,5386,231,11.8108
13,Austria,1391,164,72.4528
14,Azerbaijan,567,60,6.38434
15,Bahamas,45,118,0
16,Bahrain,574,425,0
17,Bangladesh,1625,10,1.96633
18,Barbados,19,69,0
19,Belarus,1142,120,0.463389
20,Belgium,2338,210,9.95974
21,Belize,13,39,64.69
22,Benin,170,16,0
23,Bermuda,6,88,0
24,Bhutan,63,83,100
25,Bolivia (Plurinational State of),336,32,31.4771
26,"Bonaire, Sint Eustatius and Saba",5,213,0
27,Bosnia and Herzegovina,266,70,41.4647
28,Botswana,86,39,0.131406
29,Brazil,12149,59,69.648
30,British Virgin Islands,2,85,0
31,Brunei Darussalam,127,310,0.045434
32,Bulgaria,703,97,17.2346
33,Burkina Faso,164,10,14.5007
34,Burundi,58,6,86.7925
35,Cabo Verde,7,15,21.2276
36,Cambodia,250,17,57.3116
37,Cameroon,307,14,70.8863
38,Canada,10431,296,61.9454
39,Cayman Islands,8,131,0
40,Central African Republic,23,5,85.6354
41,Chad,77,6,0
42,Chile,1613,92,28.0066
43,China2,127191,93,19.7549
44,"China, Hong Kong Special Administrative Region3",585,82,0
45,"China, Macao Special Administrative Region4",47,83,0
46,Colombia,1513,32,63.0028
47,Comoros,5,7,11.6279
48,Congo,102,23,57.7489
49,Cook Islands,1,48,0
50,Costa Rica,222,47,88.7364
51,Côte d'Ivoire,547,25,22.8228
52,Croatia,321,75,64.2841
53,Cuba,585,51,0.663532
54,Curaçao,78,502,0
55,Cyprus,82,71,6.48019
56,Czech Republic,1751,166,7.06713
57,Democratic People's Republic of Korea,612,25,70.1803
58,Democratic Republic of the Congo,888,12,99.5943
59,Denmark5,725,129,33.5377
60,Djibouti,11,13,0
61,Dominica,2,28,36.6337
62,Dominican Republic,339,33,11.2506
63,Ecuador,680,43,47.7149
64,Egypt,3422,39,8.80571
65,El Salvador,176,29,56.4451
66,Equatorial Guinea,73,91,6.36364
67,Eritrea,34,7,0.550964
68,Estonia,258,195,4.18079
69,Ethiopia,1394,15,99.9082
70,Faeroe Islands,9,179,38.5665
71,Falkland Islands (Malvinas),1,258,33.3333
72,Fiji,31,36,62.0047
73,Finland,1374,252,19.5366
74,France6,10597,166,17.0203
75,French Guiana,13,52,62.0047
76,French Polynesia,12,44,26.8556
77,Gabon,99,60,37.5
78,Gambia,14,7,0
79,Georgia,163,40,82.2249
80,Germany,13261,165,17.9015
81,Ghana,316,12,63.1026
82,Gibraltar,8,245,0
83,Greece,993,90,24.7953
84,Greenland7,9,166,78.125
85,Grenada,5,43,0
86,Guadeloupe,33,70,14.8148
87,Guam,...,...,0
88,Guatemala,452,29,49.5217
89,Guernsey,0,6,0
90,Guinea,145,12,48.4422
91,Guinea-Bissau,29,17,0
92,Guyana,34,45,0
93,Haiti,172,16,12.7602
94,Honduras,217,28,37.7632
95,Hungary,947,95,3.26363
96,Iceland,312,957,99.9724
97,India,33195,26,14.9691
98,Indonesia8,8754,35,12.189
99,Iran (Islamic Republic of),9172,119,5.70772
100,Iraq,2077,61,7.87155
101,Ireland,548,117,20.9211
102,Isle of Man,0,4,0.793651
103,Israel,997,128,0.872525
104,Italy9,6530,109,33.6672
105,Jamaica,108,39,5.6156
106,Japan10,18984,149,10.2328
107,Jersey,3,34,0
108,Jordan,325,45,0.335979
109,Kazakhstan,3548,208,8.11278
110,Kenya,873,20,73.7571
111,Kiribati,1,8,0
112,Kuwait11,1475,410,0
113,Kyrgyzstan,167,29,93.4766
114,Lao People's Democratic Republic,85,13,93.2901
115,Latvia,183,91,48.8323
116,Lebanon,289,55,6.61048
117,Lesotho,48,23,100
118,Liberia,83,19,0
119,Libya,707,113,0
120,Liechtenstein,3,79,96.4706
121,Lithuania,282,95,41.0332
122,Luxembourg,168,307,45.5332
123,Madagascar,166,7,50.8156
124,Malawi,101,6,89.1356
125,Malaysia,3417,116,7.75459
126,Maldives,15,43,0
127,Mali,66,4,64.7682
128,Malta,31,75,1.4197
129,Marshall Islands,1,28,0
130,Martinique,33,84,2.60771
131,Mauritania,51,13,0
132,Mauritius,58,46,3.53186
133,Mexico,7944,64,12.9134
134,Micronesia (Federated States of),2,21,2.94118
135,Mongolia,475,166,0
136,Montenegro,42,67,65.5815
137,Montserrat,1,153,0
138,Morocco,796,23,15.8918
139,Mozambique,469,18,94.6309
140,Myanmar,682,13,72.0421
141,Namibia,63,27,95.7944
142,Nauru,1,60,0
143,Nepal,458,16,99.6805
144,Netherlands12,3199,190,6.32466
145,New Caledonia,51,200,20.431
146,New Zealand,876,196,72.8731
147,Nicaragua,149,25,40.7639
148,Niger,87,5,0
149,Nigeria,5589,32,18.3903
150,Niue,0,65,0
151,Northern Mariana Islands,...,...,0
152,Norway,1388,273,97.6356
153,Oman,1015,260,0
154,Pakistan,2868,16,31.8768
155,Palau,3,152,18.75
156,Panama,158,42,57.5095
157,Papua New Guinea,144,20,23.9464
158,Paraguay,228,35,99.995
159,Peru,858,28,51.9686
160,Philippines,1781,18,26.1726
161,Poland,4121,107,5.5379
162,Portugal13,899,86,53.3403
163,Puerto Rico,56,15,1.08081
164,Qatar,1396,664,0
165,Republic of Korea,11007,221,2.27935
166,Republic of Moldova,93,23,5.08287
167,Réunion,59,70,28.2972
168,Romania,1339,68,34.3845
169,Russian Federation,30709,214,17.2887
170,Rwanda,95,9,35.8353
171,Saint Helena,0,40,9.09091
172,Saint Kitts and Nevis,4,73,0
173,Saint Lucia,6,33,0
174,Saint Pierre and Miquelon,1,162,2.12766
175,Saint Vincent and the Grenadines,3,28,16.6667
176,Samoa,4,22,31.3559
177,Sao Tome and Principe,3,14,10.4478
178,Saudi Arabia14,7985,264,0.000352
179,Senegal,154,11,1.99824
180,Serbia15,618,69,27.2162
181,Seychelles,9,94,1.9774
182,Sierra Leone,67,11,64.0244
183,Singapore,1120,207,0
184,Sint Maarten (Dutch part),12,327,0
185,Slovakia,711,131,20.2171
186,Slovenia,287,139,31.8642
187,Solomon Islands,6,11,0
188,Somalia,126,12,0
189,South Africa,6341,119,1.68702
190,South Sudan,28,2,0.423729
191,Spain16,4923,106,37.9686
192,Sri Lanka,388,19,59.5732
193,State of Palestine,61,14,0
194,Sudan,608,16,78.4105
195,Suriname,34,65,22.0238
196,Swaziland,49,39,40.678
197,Sweden,2044,212,46.5985
198,Switzerland17,1113,136,57.7455
199,Syrian Arab Republic,542,28,11.5683
200,Tajikistan,106,13,99.7429
201,Thailand,5336,79,4.30519
202,The former Yugoslav Republic of Macedonia,117,56,26.1405
203,Timor-Leste,7,6,0
204,Togo,134,19,80.1802
205,Tonga,3,28,0
206,Trinidad and Tobago,824,611,0
207,Tunisia,430,39,3.49255
208,Turkey,4897,64,28.5367
209,Turkmenistan,1102,210,0
210,Turks and Caicos Islands,3,85,0
211,Tuvalu,...,...,0
212,Uganda,452,12,68.0182
213,Ukraine18,4844,107,8.06731
214,United Arab Emirates,2710,300,0
215,United Kingdom of Great Britain and Northern I...,7920,124,10.6005
216,United Republic of Tanzania,994,20,31.0728
217,United States of America20,90838,286,11.571
218,United States Virgin Islands,...,...,0
219,Uruguay,196,58,71.605
220,Uzbekistan,1798,62,21.3284
221,Vanuatu,3,10,14.7059
222,Venezuela (Bolivarian Republic of),2871,95,67.8345
223,Viet Nam,2554,28,45.3215
224,Wallis and Futuna Islands,0,26,0
225,Yemen,344,13,0
226,Zambia,400,26,99.7147
227,Zimbabwe,480,32,52.5361

In [5]:
Energy.rename(columns={'Unnamed: 2':'Country',
                       'Renewable Electricity Production':'%Renewable'},
             inplace=True)

In [6]:
Energy.reset_index(drop=True,inplace=True)

In [7]:
#1.1.2
#1.1.2
Energy.replace({'...':np.NaN},inplace=True)

In [8]:
Energy

,Country,Energy Supply,Energy Supply per capita,%Renewable
0,Afghanistan,321.0,10.0,78.669280
1,Albania,102.0,35.0,100.000000
2,Algeria,1959.0,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.0,121.0,88.695650
5,Angola,642.0,27.0,70.909090
6,Anguilla,2.0,136.0,0.000000
7,Antigua and Barbuda,8.0,84.0,0.000000
8,Argentina,3378.0,79.0,24.064520
9,Armenia,143.0,48.0,28.236060
10,Aruba,12.0,120.0,14.870690
11,Australia1,5386.0,231.0,11.810810
12,Austria,1391.0,164.0,72.452820
13,Azerbaijan,567.0,60.0,6.384345
14,Bahamas,45.0,118.0,0.000000
15,Bahrain,574.0,425.0,0.000000
16,Bangladesh,1625.0,10.0,1.966329
17,Barbados,19.0,69.0,0.000000
18,Belarus,1142.0,120.0,0.463389
19,Belgium,2338.0,210.0,9.959739
20,Belize,13.0,39.0,64.690030
21,Benin,170.0,16.0,0.000000
22,Bermuda,6.0,88.0,0.000000
23,Bhutan,63.0,83.0,100.000000
24,Bolivia (Plurinational State of),336.0,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.0,213.0,0.000000
26,Bosnia and Herzegovina,266.0,70.0,41.464670
27,Botswana,86.0,39.0,0.131406
28,Brazil,12149.0,59.0,69.648030
29,British Virgin Islands,2.0,85.0,0.000000
30,Brunei Darussalam,127.0,310.0,0.045434
31,Bulgaria,703.0,97.0,17.234610
32,Burkina Faso,164.0,10.0,14.500680
33,Burundi,58.0,6.0,86.792450
34,Cabo Verde,7.0,15.0,21.227620
35,Cambodia,250.0,17.0,57.311590
36,Cameroon,307.0,14.0,70.886260
37,Canada,10431.0,296.0,61.945430
38,Cayman Islands,8.0,131.0,0.000000
39,Central African Republic,23.0,5.0,85.635360
40,Chad,77.0,6.0,0.000000
41,Chile,1613.0,92.0,28.006570
42,China2,127191.0,93.0,19.754910
43,"China, Hong Kong Special Administrative Region3",585.0,82.0,0.000000
44,"China, Macao Special Administrative Region4",47.0,83.0,0.000000
45,Colombia,1513.0,32.0,63.002840
46,Comoros,5.0,7.0,11.627910
47,Congo,102.0,23.0,57.748870
48,Cook Islands,1.0,48.0,0.000000
49,Costa Rica,222.0,47.0,88.736420
50,Côte d'Ivoire,547.0,25.0,22.822780
51,Croatia,321.0,75.0,64.284120
52,Cuba,585.0,51.0,0.663532
53,Curaçao,78.0,502.0,0.000000
54,Cyprus,82.0,71.0,6.480186
55,Czech Republic,1751.0,166.0,7.067134
56,Democratic People's Republic of Korea,612.0,25.0,70.180290
57,Democratic Republic of the Congo,888.0,12.0,99.594300
58,Denmark5,725.0,129.0,33.537660
59,Djibouti,11.0,13.0,0.000000
60,Dominica,2.0,28.0,36.633660
61,Dominican Republic,339.0,33.0,11.250600
62,Ecuador,680.0,43.0,47.714860
63,Egypt,3422.0,39.0,8.805713
64,El Salvador,176.0,29.0,56.445050
65,Equatorial Guinea,73.0,91.0,6.363636
66,Eritrea,34.0,7.0,0.550964
67,Estonia,258.0,195.0,4.180791
68,Ethiopia,1394.0,15.0,99.908250
69,Faeroe Islands,9.0,179.0,38.566550
70,Falkland Islands (Malvinas),1.0,258.0,33.333330
71,Fiji,31.0,36.0,62.004660
72,Finland,1374.0,252.0,19.536570
73,France6,10597.0,166.0,17.020280
74,French Guiana,13.0,52.0,62.004660
75,French Polynesia,12.0,44.0,26.855600
76,Gabon,99.0,60.0,37.500000
77,Gambia,14.0,7.0,0.000000
78,Georgia,163.0,40.0,82.224870
79,Germany,13261.0,165.0,17.901530
80,Ghana,316.0,12.0,63.102630
81,Gibraltar,8.0,245.0,0.000000
82,Greece,993.0,90.0,24.795280
83,Greenland7,9.0,166.0,78.125000
84,Grenada,5.0,43.0,0.000000
85,Guadeloupe,33.0,70.0,14.814810
86,Guam,NaN,NaN,0.000000
87,Guatemala,452.0,29.0,49.521680
88,Guernsey,0.0,6.0,0.000000
89,Guinea,145.0,12.0,48.442210
90,Guinea-Bissau,29.0,17.0,0.000000
91,Guyana,34.0,45.0,0.000000
92,Haiti,172.0,16.0,12.760180
93,Honduras,217.0,28.0,37.763190
94,Hungary,947.0,95.0,3.263634
95,Iceland,312.0,957.0,99.972400
96,India,33195.0,26.0,14.969080
97,Indonesia8,8754.0,35.0,12.189040
98,Iran (Islamic Republic of),9172.0,119.0,5.707721
99,Iraq,2077.0,61.0,7.871554
100,Ireland,548.0,117.0,20.921060
101,Isle of Man,0.0,4.0,0.793651
102,Israel,997.0,128.0,0.872525
103,Italy9,6530.0,109.0,33.667230
104,Jamaica,108.0,39.0,5.615602
105,Japan10,18984.0,149.0,10.232820
106,Jersey,3.0,34.0,0.000000
107,Jordan,325.0,45.0,0.335979
108,Kazakhstan,3548.0,208.0,8.112784
109,Kenya,873.0,20.0,73.757100
110,Kiribati,1.0,8.0,0.000000
111,Kuwait11,1475.0,410.0,0.000000
112,Kyrgyzstan,167.0,29.0,93.476550
113,Lao People's Democratic Republic,85.0,13.0,93.290090
114,Latvia,183.0,91.0,48.832340
115,Lebanon,289.0,55.0,6.610478
116,Lesotho,48.0,23.0,100.000000
117,Liberia,83.0,19.0,0.000000
118,Libya,707.0,113.0,0.000000
119,Liechtenstein,3.0,79.0,96.470590
120,Lithuania,282.0,95.0,41.033180
121,Luxembourg,168.0,307.0,45.533240
122,Madagascar,166.0,7.0,50.815560
123,Malawi,101.0,6.0,89.135650
124,Malaysia,3417.0,116.0,7.754589
125,Maldives,15.0,43.0,0.000000
126,Mali,66.0,4.0,64.768210
127,Malta,31.0,75.0,1.419698
128,Marshall Islands,1.0,28.0,0.000000
129,Martinique,33.0,84.0,2.607710
130,Mauritania,51.0,13.0,0.000000
131,Mauritius,58.0,46.0,3.531856
132,Mexico,7944.0,64.0,12.913400
133,Micronesia (Federated States of),2.0,21.0,2.941176
134,Mongolia,475.0,166.0,0.000000
135,Montenegro,42.0,67.0,65.581520
136,Montserrat,1.0,153.0,0.000000
137,Morocco,796.0,23.0,15.891800
138,Mozambique,469.0,18.0,94.630870
139,Myanmar,682.0,13.0,72.042130
140,Namibia,63.0,27.0,95.794390
141,Nauru,1.0,60.0,0.000000
142,Nepal,458.0,16.0,99.680510
143,Netherlands12,3199.0,190.0,6.324659
144,New Caledonia,51.0,200.0,20.430970
145,New Zealand,876.0,196.0,72.873130
146,Nicaragua,149.0,25.0,40.763870
147,Niger,87.0,5.0,0.000000
148,Nigeria,5589.0,32.0,18.390250
149,Niue,0.0,65.0,0.000000
150,Northern Mariana Islands,NaN,NaN,0.000000
151,Norway,1388.0,273.0,97.635580
152,Oman,1015.0,260.0,0.000000
153,Pakistan,2868.0,16.0,31.876840
154,Palau,3.0,152.0,18.750000
155,Panama,158.0,42.0,57.509480
156,Papua New Guinea,144.0,20.0,23.946360
157,Paraguay,228.0,35.0,99.995030
158,Peru,858.0,28.0,51.968610
159,Philippines,1781.0,18.0,26.172640
160,Poland,4121.0,107.0,5.537899
161,Portugal13,899.0,86.0,53.340300
162,Puerto Rico,56.0,15.0,1.080808
163,Qatar,1396.0,664.0,0.000000
164,Republic of Korea,11007.0,221.0,2.279353
165,Republic of Moldova,93.0,23.0,5.082873
166,Réunion,59.0,70.0,28.297190
167,Romania,1339.0,68.0,34.384500
168,Russian Federation,30709.0,214.0,17.288680
169,Rwanda,95.0,9.0,35.835350
170,Saint Helena,0.0,40.0,9.090909
171,Saint Kitts and Nevis,4.0,73.0,0.000000
172,Saint Lucia,6.0,33.0,0.000000
173,Saint Pierre and Miquelon,1.0,162.0,2.127660
174,Saint Vincent and the Grenadines,3.0,28.0,16.666670
175,Samoa,4.0,22.0,31.355930
176,Sao Tome and Principe,3.0,14.0,10.447760
177,Saudi Arabia14,7985.0,264.0,0.000352
178,Senegal,154.0,11.0,1.998237
179,Serbia15,618.0,69.0,27.216190
180,Seychelles,9.0,94.0,1.977401
181,Sierra Leone,67.0,11.0,64.024390
182,Singapore,1120.0,207.0,0.000000
183,Sint Maarten (Dutch part),12.0,327.0,0.000000
184,Slovakia,711.0,131.0,20.217120
185,Slovenia,287.0,139.0,31.864240
186,Solomon Islands,6.0,11.0,0.000000
187,Somalia,126.0,12.0,0.000000
188,South Africa,6341.0,119.0,1.687019
189,South Sudan,28.0,2.0,0.423729
190,Spain16,4923.0,106.0,37.968590
191,Sri Lanka,388.0,19.0,59.573230
192,State of Palestine,61.0,14.0,0.000000
193,Sudan,608.0,16.0,78.410480
194,Suriname,34.0,65.0,22.023810
195,Swaziland,49.0,39.0,40.677970
196,Sweden,2044.0,212.0,46.598460
197,Switzerland17,1113.0,136.0,57.745480
198,Syrian Arab Republic,542.0,28.0,11.568270
199,Tajikistan,106.0,13.0,99.742920
200,Thailand,5336.0,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,117.0,56.0,26.140470
202,Timor-Leste,7.0,6.0,0.000000
203,Togo,134.0,19.0,80.180180
204,Tonga,3.0,28.0,0.000000
205,Trinidad and Tobago,824.0,611.0,0.000000
206,Tunisia,430.0,39.0,3.492547
207,Turkey,4897.0,64.0,28.536690
208,Turkmenistan,1102.0,210.0,0.000000
209,Turks and Caicos Islands,3.0,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,452.0,12.0,68.018180
212,Ukraine18,4844.0,107.0,8.067312
213,United Arab Emirates,2710.0,300.0,0.000000
214,United Kingdom of Great Britain and Northern I...,7920.0,124.0,10.600470
215,United Republic of Tanzania,994.0,20.0,31.072840
216,United States of America20,90838.0,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,196.0,58.0,71.605040
219,Uzbekistan,1798.0,62.0,21.328410
220,Vanuatu,3.0,10.0,14.705880
221,Venezuela (Bolivarian Republic of),2871.0,95.0,67.834520
222,Viet Nam,2554.0,28.0,45.321520
223,Wallis and Futuna Islands,0.0,26.0,0.000000
224,Yemen,344.0,13.0,0.000000
225,Zambia,400.0,26.0,99.714670
226,Zimbabwe,480.0,32.0,52.536120

In [9]:
Energy['Energy Supply']=Energy['Energy Supply'].map(lambda x:x*1000000)

In [10]:
#去除数字
Energy['Country']=Energy['Country'].str.replace('\d*','')

In [11]:
#去除括号及里面内容
Energy['Country']=Energy['Country'].str.replace('\(.*\)','')

In [13]:
#替换国家名
t=Energy[(Energy['Country']=='Republic of Korea') |
  (Energy['Country']=="United States of America") |
  (Energy['Country']=="United Kingdom of Great Britain and Northern Ireland") |
  (Energy['Country']=="China, Hong Kong Special Administrative Region")]
t

,Country,Energy Supply,Energy Supply per capita,%Renewable
43,"China, Hong Kong Special Administrative Region",5.850000e+08,82.0,0.000000
164,Republic of Korea,1.100700e+10,221.0,2.279353
214,United Kingdom of Great Britain and Northern I...,7.920000e+09,124.0,10.600470
216,United States of America,9.083800e+10,286.0,11.570980

In [14]:
t['Country']

43        China, Hong Kong Special Administrative Region
164                                    Republic of Korea
214    United Kingdom of Great Britain and Northern I...
216                             United States of America
Name: Country, dtype: object

In [15]:
t1=t['Country'].map({"Republic of Korea": "South Korea",
  "United States of America": "United States",
  "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
  "China, Hong Kong Special Administrative Region": "Hong Kong"})

In [16]:
t1

43          Hong Kong
164       South Korea
214    United Kingdom
216     United States
Name: Country, dtype: object

In [17]:
Energy[(Energy['Country']=='Republic of Korea') |
  (Energy['Country']=="United States of America") |
  (Energy['Country']=="United Kingdom of Great Britain and Northern Ireland") |
  (Energy['Country']=="China, Hong Kong Special Administrative Region")]['Country']=t1

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [18]:
Energy

,Country,Energy Supply,Energy Supply per capita,%Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
5,Angola,6.420000e+08,27.0,70.909090
6,Anguilla,2.000000e+06,136.0,0.000000
7,Antigua and Barbuda,8.000000e+06,84.0,0.000000
8,Argentina,3.378000e+09,79.0,24.064520
9,Armenia,1.430000e+08,48.0,28.236060
10,Aruba,1.200000e+07,120.0,14.870690
11,Australia,5.386000e+09,231.0,11.810810
12,Austria,1.391000e+09,164.0,72.452820
13,Azerbaijan,5.670000e+08,60.0,6.384345
14,Bahamas,4.500000e+07,118.0,0.000000
15,Bahrain,5.740000e+08,425.0,0.000000
16,Bangladesh,1.625000e+09,10.0,1.966329
17,Barbados,1.900000e+07,69.0,0.000000
18,Belarus,1.142000e+09,120.0,0.463389
19,Belgium,2.338000e+09,210.0,9.959739
20,Belize,1.300000e+07,39.0,64.690030
21,Benin,1.700000e+08,16.0,0.000000
22,Bermuda,6.000000e+06,88.0,0.000000
23,Bhutan,6.300000e+07,83.0,100.000000
24,Bolivia,3.360000e+08,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0.000000
26,Bosnia and Herzegovina,2.660000e+08,70.0,41.464670
27,Botswana,8.600000e+07,39.0,0.131406
28,Brazil,1.214900e+10,59.0,69.648030
29,British Virgin Islands,2.000000e+06,85.0,0.000000
30,Brunei Darussalam,1.270000e+08,310.0,0.045434
31,Bulgaria,7.030000e+08,97.0,17.234610
32,Burkina Faso,1.640000e+08,10.0,14.500680
33,Burundi,5.800000e+07,6.0,86.792450
34,Cabo Verde,7.000000e+06,15.0,21.227620
35,Cambodia,2.500000e+08,17.0,57.311590
36,Cameroon,3.070000e+08,14.0,70.886260
37,Canada,1.043100e+10,296.0,61.945430
38,Cayman Islands,8.000000e+06,131.0,0.000000
39,Central African Republic,2.300000e+07,5.0,85.635360
40,Chad,7.700000e+07,6.0,0.000000
41,Chile,1.613000e+09,92.0,28.006570
42,China,1.271910e+11,93.0,19.754910
43,"China, Hong Kong Special Administrative Region",5.850000e+08,82.0,0.000000
44,"China, Macao Special Administrative Region",4.700000e+07,83.0,0.000000
45,Colombia,1.513000e+09,32.0,63.002840
46,Comoros,5.000000e+06,7.0,11.627910
47,Congo,1.020000e+08,23.0,57.748870
48,Cook Islands,1.000000e+06,48.0,0.000000
49,Costa Rica,2.220000e+08,47.0,88.736420
50,Côte d'Ivoire,5.470000e+08,25.0,22.822780
51,Croatia,3.210000e+08,75.0,64.284120
52,Cuba,5.850000e+08,51.0,0.663532
53,Curaçao,7.800000e+07,502.0,0.000000
54,Cyprus,8.200000e+07,71.0,6.480186
55,Czech Republic,1.751000e+09,166.0,7.067134
56,Democratic People's Republic of Korea,6.120000e+08,25.0,70.180290
57,Democratic Republic of the Congo,8.880000e+08,12.0,99.594300
58,Denmark,7.250000e+08,129.0,33.537660
59,Djibouti,1.100000e+07,13.0,0.000000
60,Dominica,2.000000e+06,28.0,36.633660
61,Dominican Republic,3.390000e+08,33.0,11.250600
62,Ecuador,6.800000e+08,43.0,47.714860
63,Egypt,3.422000e+09,39.0,8.805713
64,El Salvador,1.760000e+08,29.0,56.445050
65,Equatorial Guinea,7.300000e+07,91.0,6.363636
66,Eritrea,3.400000e+07,7.0,0.550964
67,Estonia,2.580000e+08,195.0,4.180791
68,Ethiopia,1.394000e+09,15.0,99.908250
69,Faeroe Islands,9.000000e+06,179.0,38.566550
70,Falkland Islands,1.000000e+06,258.0,33.333330
71,Fiji,3.100000e+07,36.0,62.004660
72,Finland,1.374000e+09,252.0,19.536570
73,France,1.059700e+10,166.0,17.020280
74,French Guiana,1.300000e+07,52.0,62.004660
75,French Polynesia,1.200000e+07,44.0,26.855600
76,Gabon,9.900000e+07,60.0,37.500000
77,Gambia,1.400000e+07,7.0,0.000000
78,Georgia,1.630000e+08,40.0,82.224870
79,Germany,1.326100e+10,165.0,17.901530
80,Ghana,3.160000e+08,12.0,63.102630
81,Gibraltar,8.000000e+06,245.0,0.000000
82,Greece,9.930000e+08,90.0,24.795280
83,Greenland,9.000000e+06,166.0,78.125000
84,Grenada,5.000000e+06,43.0,0.000000
85,Guadeloupe,3.300000e+07,70.0,14.814810
86,Guam,NaN,NaN,0.000000
87,Guatemala,4.520000e+08,29.0,49.521680
88,Guernsey,0.000000e+00,6.0,0.000000
89,Guinea,1.450000e+08,12.0,48.442210
90,Guinea-Bissau,2.900000e+07,17.0,0.000000
91,Guyana,3.400000e+07,45.0,0.000000
92,Haiti,1.720000e+08,16.0,12.760180
93,Honduras,2.170000e+08,28.0,37.763190
94,Hungary,9.470000e+08,95.0,3.263634
95,Iceland,3.120000e+08,957.0,99.972400
96,India,3.319500e+10,26.0,14.969080
97,Indonesia,8.754000e+09,35.0,12.189040
98,Iran,9.172000e+09,119.0,5.707721
99,Iraq,2.077000e+09,61.0,7.871554
100,Ireland,5.480000e+08,117.0,20.921060
101,Isle of Man,0.000000e+00,4.0,0.793651
102,Israel,9.970000e+08,128.0,0.872525
103,Italy,6.530000e+09,109.0,33.667230
104,Jamaica,1.080000e+08,39.0,5.615602
105,Japan,1.898400e+10,149.0,10.232820
106,Jersey,3.000000e+06,34.0,0.000000
107,Jordan,3.250000e+08,45.0,0.335979
108,Kazakhstan,3.548000e+09,208.0,8.112784
109,Kenya,8.730000e+08,20.0,73.757100
110,Kiribati,1.000000e+06,8.0,0.000000
111,Kuwait,1.475000e+09,410.0,0.000000
112,Kyrgyzstan,1.670000e+08,29.0,93.476550
113,Lao People's Democratic Republic,8.500000e+07,13.0,93.290090
114,Latvia,1.830000e+08,91.0,48.832340
115,Lebanon,2.890000e+08,55.0,6.610478
116,Lesotho,4.800000e+07,23.0,100.000000
117,Liberia,8.300000e+07,19.0,0.000000
118,Libya,7.070000e+08,113.0,0.000000
119,Liechtenstein,3.000000e+06,79.0,96.470590
120,Lithuania,2.820000e+08,95.0,41.033180
121,Luxembourg,1.680000e+08,307.0,45.533240
122,Madagascar,1.660000e+08,7.0,50.815560
123,Malawi,1.010000e+08,6.0,89.135650
124,Malaysia,3.417000e+09,116.0,7.754589
125,Maldives,1.500000e+07,43.0,0.000000
126,Mali,6.600000e+07,4.0,64.768210
127,Malta,3.100000e+07,75.0,1.419698
128,Marshall Islands,1.000000e+06,28.0,0.000000
129,Martinique,3.300000e+07,84.0,2.607710
130,Mauritania,5.100000e+07,13.0,0.000000
131,Mauritius,5.800000e+07,46.0,3.531856
132,Mexico,7.944000e+09,64.0,12.913400
133,Micronesia,2.000000e+06,21.0,2.941176
134,Mongolia,4.750000e+08,166.0,0.000000
135,Montenegro,4.200000e+07,67.0,65.581520
136,Montserrat,1.000000e+06,153.0,0.000000
137,Morocco,7.960000e+08,23.0,15.891800
138,Mozambique,4.690000e+08,18.0,94.630870
139,Myanmar,6.820000e+08,13.0,72.042130
140,Namibia,6.300000e+07,27.0,95.794390
141,Nauru,1.000000e+06,60.0,0.000000
142,Nepal,4.580000e+08,16.0,99.680510
143,Netherlands,3.199000e+09,190.0,6.324659
144,New Caledonia,5.100000e+07,200.0,20.430970
145,New Zealand,8.760000e+08,196.0,72.873130
146,Nicaragua,1.490000e+08,25.0,40.763870
147,Niger,8.700000e+07,5.0,0.000000
148,Nigeria,5.589000e+09,32.0,18.390250
149,Niue,0.000000e+00,65.0,0.000000
150,Northern Mariana Islands,NaN,NaN,0.000000
151,Norway,1.388000e+09,273.0,97.635580
152,Oman,1.015000e+09,260.0,0.000000
153,Pakistan,2.868000e+09,16.0,31.876840
154,Palau,3.000000e+06,152.0,18.750000
155,Panama,1.580000e+08,42.0,57.509480
156,Papua New Guinea,1.440000e+08,20.0,23.946360
157,Paraguay,2.280000e+08,35.0,99.995030
158,Peru,8.580000e+08,28.0,51.968610
159,Philippines,1.781000e+09,18.0,26.172640
160,Poland,4.121000e+09,107.0,5.537899
161,Portugal,8.990000e+08,86.0,53.340300
162,Puerto Rico,5.600000e+07,15.0,1.080808
163,Qatar,1.396000e+09,664.0,0.000000
164,Republic of Korea,1.100700e+10,221.0,2.279353
165,Republic of Moldova,9.300000e+07,23.0,5.082873
166,Réunion,5.900000e+07,70.0,28.297190
167,Romania,1.339000e+09,68.0,34.384500
168,Russian Federation,3.070900e+10,214.0,17.288680
169,Rwanda,9.500000e+07,9.0,35.835350
170,Saint Helena,0.000000e+00,40.0,9.090909
171,Saint Kitts and Nevis,4.000000e+06,73.0,0.000000
172,Saint Lucia,6.000000e+06,33.0,0.000000
173,Saint Pierre and Miquelon,1.000000e+06,162.0,2.127660
174,Saint Vincent and the Grenadines,3.000000e+06,28.0,16.666670
175,Samoa,4.000000e+06,22.0,31.355930
176,Sao Tome and Principe,3.000000e+06,14.0,10.447760
177,Saudi Arabia,7.985000e+09,264.0,0.000352
178,Senegal,1.540000e+08,11.0,1.998237
179,Serbia,6.180000e+08,69.0,27.216190
180,Seychelles,9.000000e+06,94.0,1.977401
181,Sierra Leone,6.700000e+07,11.0,64.024390
182,Singapore,1.120000e+09,207.0,0.000000
183,Sint Maarten,1.200000e+07,327.0,0.000000
184,Slovakia,7.110000e+08,131.0,20.217120
185,Slovenia,2.870000e+08,139.0,31.864240
186,Solomon Islands,6.000000e+06,11.0,0.000000
187,Somalia,1.260000e+08,12.0,0.000000
188,South Africa,6.341000e+09,119.0,1.687019
189,South Sudan,2.800000e+07,2.0,0.423729
190,Spain,4.923000e+09,106.0,37.968590
191,Sri Lanka,3.880000e+08,19.0,59.573230
192,State of Palestine,6.100000e+07,14.0,0.000000
193,Sudan,6.080000e+08,16.0,78.410480
194,Suriname,3.400000e+07,65.0,22.023810
195,Swaziland,4.900000e+07,39.0,40.677970
196,Sweden,2.044000e+09,212.0,46.598460
197,Switzerland,1.113000e+09,136.0,57.745480
198,Syrian Arab Republic,5.420000e+08,28.0,11.568270
199,Tajikistan,1.060000e+08,13.0,99.742920
200,Thailand,5.336000e+09,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,1.170000e+08,56.0,26.140470
202,Timor-Leste,7.000000e+06,6.0,0.000000
203,Togo,1.340000e+08,19.0,80.180180
204,Tonga,3.000000e+06,28.0,0.000000
205,Trinidad and Tobago,8.240000e+08,611.0,0.000000
206,Tunisia,4.300000e+08,39.0,3.492547
207,Turkey,4.897000e+09,64.0,28.536690
208,Turkmenistan,1.102000e+09,210.0,0.000000
209,Turks and Caicos Islands,3.000000e+06,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,4.520000e+08,12.0,68.018180
212,Ukraine,4.844000e+09,107.0,8.067312
213,United Arab Emirates,2.710000e+09,300.0,0.000000
214,United Kingdom of Great Britain and Northern I...,7.920000e+09,124.0,10.600470
215,United Republic of Tanzania,9.940000e+08,20.0,31.072840
216,United States of America,9.083800e+10,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,1.960000e+08,58.0,71.605040
219,Uzbekistan,1.798000e+09,62.0,21.328410
220,Vanuatu,3.000000e+06,10.0,14.705880
221,Venezuela,2.871000e+09,95.0,67.834520
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120

In [23]:
#1.2
GDP=pd.read_csv('world_bank.csv',skiprows=4)
GDP.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.022871e+09,1.070430e+09,1.157667e+09,1.247831e+09,1.317944e+09,1.325090e+09,1.368868e+09,1.407725e+09,1.428320e+09,1.428913e+09,1.460474e+09,1.458539e+09,1.476720e+09,1.502859e+09,1.529681e+09,1.565191e+09,1.616112e+09,1.705759e+09,1.792656e+09,1.879188e+09,1.950248e+09,1.999901e+09,2.018485e+09,1.997664e+09,2.045272e+09,2.101671e+09,2.199393e+09,2.398827e+09,2.475464e+09,2.576935e+09,2.606977e+09,2.765137e+09,2.942848e+09,3.296693e+09,3.562720e+09,3.842027e+09,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN

In [26]:
t2=GDP[ (GDP['Country Name']=='Korea, Rep.')|
     (GDP['Country Name']=='Iran, Islamic Rep.')|
     (GDP['Country Name']=='Hong Kong SAR, China') ]    
t2

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
93,"Hong Kong SAR, China",HKG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.764691e+10,1.796359e+10,1.825160e+10,1.887167e+10,2.101239e+10,2.294697e+10,2.462054e+10,2.723322e+10,3.057744e+10,3.131591e+10,3.147002e+10,3.655688e+10,4.084348e+10,4.421754e+10,4.932766e+10,5.431386e+10,5.934375e+10,6.109426e+10,6.474588e+10,7.120350e+10,7.174253e+10,7.967440e+10,9.034956e+10,9.803982e+10,1.002723e+11,1.041131e+11,1.100496e+11,1.169111e+11,1.241609e+11,1.316553e+11,1.347805e+11,1.405201e+11,1.476861e+11,1.389983e+11,1.424825e+11,1.534017e+11,1.542619e+11,1.568175e+11,1.616104e+11,1.756706e+11,1.886494e+11,2.019164e+11,2.149698e+11,2.195440e+11,2.141452e+11,2.286377e+11,2.396459e+11,2.437206e+11,2.512081e+11,2.577757e+11,2.638606e+11
109,"Iran, Islamic Rep.",IRN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.500820e+10,6.072406e+10,6.552689e+10,7.014134e+10,7.608598e+10,8.904776e+10,9.929040e+10,1.104634e+11,1.263747e+11,1.459838e+11,1.619364e+11,1.841242e+11,2.108204e+11,2.265090e+11,2.396489e+11,2.388671e+11,2.824853e+11,2.746503e+11,2.393829e+11,2.106072e+11,1.651168e+11,1.557105e+11,1.917905e+11,2.130538e+11,1.978421e+11,2.015371e+11,1.818168e+11,1.815039e+11,1.704649e+11,1.809180e+11,2.055136e+11,2.316471e+11,2.392867e+11,2.357668e+11,2.317628e+11,2.373275e+11,2.523991e+11,2.558075e+11,2.611283e+11,2.663579e+11,2.819279e+11,2.886721e+11,3.119935e+11,3.389475e+11,3.536465e+11,3.685304e+11,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
123,"Korea, Rep.",KOR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.757696e+10,2.893825e+10,2.964966e+10,3.247578e+10,3.493136e+10,3.674434e+10,4.141087e+10,4.393695e+10,4.907749e+10,5.599745e+10,6.320350e+10,6.980272e+10,7.434747e+10,8.534161e+10,9.334828e+10,1.001977e+11,1.136799e+11,1.271143e+11,1.402040e+11,1.519667e+11,1.490934e+11,1.601324e+11,1.734095e+11,1.945342e+11,2.137135e+11,2.296799e+11,2.577923e+11,2.894131e+11,3.231599e+11,3.449798e+11,3.770537e+11,4.136766e+11,4.375260e+11,4.652187e+11,5.060272e+11,5.512186e+11,5.908287e+11,6.249003e+11,5.891941e+11,6.524181e+11,7.100350e+11,7.421663e+11,7.973274e+11,8.207146e+11,8.609284e+11,8.947086e+11,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12

In [28]:
t3=t2['Country Name'].map({'Korea, Rep.':'South Korea',
                           'Iran, Islamic Rep.':'Iran',
                       'Hong Kong SAR, China':'Hong Kong'})
t3

93       Hong Kong
109           Iran
123    South Korea
Name: Country Name, dtype: object

In [29]:
GDP[ (GDP['Country Name']=='Korea, Rep.')|
     (GDP['Country Name']=='Iran, Islamic Rep.')|
     (GDP['Country Name']=='Hong Kong SAR, China') ]['Country name']=t3

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [32]:
#1.3
ScimEn=pd.read_excel('scimagojr-3.xlsx')

In [33]:
#1.4
ScimEn.head(3)

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134

In [35]:
GDP.head(1)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN

In [37]:
Energy.head(3)

       Country  Energy Supply  Energy Supply per capita  %Renewable
0  Afghanistan   3.210000e+08                      10.0    78.66928
1      Albania   1.020000e+08                      35.0   100.00000
2      Algeria   1.959000e+09                      51.0     0.55101

In [60]:
GDP.rename(columns={'Country Name':'Country'},inplace=True)

In [105]:
F=pd.merge(pd.merge(ScimEn,Energy,on='Country',how='outer'),GDP,how='outer',on='Country')
F.head(1)

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,1.0,China,127050.0,126767.0,597237.0,411683.0,4.7,138.0,1.271910e+11,93.0,19.75491,CHN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.262508e+11,9.178435e+10,8.664442e+10,9.548215e+10,1.129554e+11,1.321578e+11,1.462987e+11,1.379597e+11,1.323033e+11,1.546626e+11,1.846671e+11,1.975938e+11,2.051024e+11,2.213055e+11,2.263955e+11,2.460919e+11,2.421544e+11,2.605582e+11,2.915174e+11,3.136728e+11,3.381602e+11,3.556513e+11,3.877182e+11,4.294052e+11,4.947051e+11,5.617541e+11,6.118951e+11,6.836084e+11,7.608605e+11,7.929275e+11,8.241198e+11,9.004974e+11,1.029057e+12,1.172483e+12,1.325821e+12,1.471580e+12,1.617630e+12,1.766887e+12,1.905650e+12,2.050825e+12,2.223695e+12,2.408226e+12,2.627155e+12,2.890396e+12,3.181621e+12,3.542812e+12,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12

In [106]:
F.set_index('Country',inplace=True)

In [107]:
F.shape

(328, 69)

In [108]:
temp=list(F.columns)[:10]+list(F.columns)[-10:]
temp

['Rank',
 'Documents',
 'Citable documents',
 'Citations',
 'Self-citations',
 'Citations per document',
 'H index',
 'Energy Supply',
 'Energy Supply per capita',
 '%Renewable',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015']

In [109]:
F=F[temp]
F.shape

(328, 20)

In [110]:
F[(F.Rank>=1) & (F.Rank<=15)]

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,NaN,NaN,NaN,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,NaN,NaN,NaN,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.94543,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.90153,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.02028,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.66723,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.96859,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.81081,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [111]:
F=F[(F.Rank>=1) & (F.Rank<=15)]

In [112]:
F

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,NaN,NaN,NaN,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,NaN,NaN,NaN,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.94543,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.90153,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.02028,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.66723,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.96859,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.81081,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [113]:
F.shape

(15, 20)

In [3]:
def quesion1():
    import pandas as pd
    import numpy as np
    ###1.构建DataFrame:Energy
    
    
    #1.1.1
    #导数据,skiprows=16,skipfooter=38 跳过读取前16行,末尾38行
    Energy=pd.read_excel('Energy Indicators.xls',skiprows=16,skipfooter=38)
    
    #截取所需部分数据
    Energy=Energy.iloc[1:,2:]
    
    #修改列名
    Energy.rename(columns={'Unnamed: 2':'Country',
                       'Renewable Electricity Production':'%Renewable'},
             inplace=True)
    
    #重置索引
    Energy.reset_index(drop=True,inplace=True)
    
    
    #1.1.2
    #将'...'替换为np.NaN
    Energy.replace({'...':np.NaN},inplace=True)
    
    # 将`Energy Supply`转化为gigajoules（1 petajoule = 1,000,000 gigajoules）
    Energy['Energy Supply']=Energy['Energy Supply'].map(lambda x:x*1000000)
    
    #去除数字
    Energy['Country']=Energy['Country'].str.replace('\d*','')    
    
    #去除()及里边内容
    Energy['Country']=Energy['Country'].str.replace('\(.*\)','')    
    
    #替换部分国家名
    temp=Energy[(Energy['Country']=='Republic of Korea') | (Energy['Country']=="United States of America") |
    (Energy['Country']=="United Kingdom of Great Britain and Northern Ireland") |
    (Energy['Country']=="China, Hong Kong Special Administrative Region")]
    
    temp1=temp['Country'].map({"Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    Energy[(Energy['Country']=='Republic of Korea') |
    (Energy['Country']=="United States of America") |
    (Energy['Country']=="United Kingdom of Great Britain and Northern Ireland") |
    (Energy['Country']=="China, Hong Kong Special Administrative Region")]['Country']=temp1
    
    
    ###1.2 构建DataFrame:GDP
    GDP=pd.read_csv('world_bank.csv',skiprows=4)
    #替换国家名
    temp2=GDP[ (GDP['Country Name']=='Korea, Rep.')|
    (GDP['Country Name']=='Iran, Islamic Rep.')|
    (GDP['Country Name']=='Hong Kong SAR, China') ]  
    
    temp3=temp2['Country Name'].map({'Korea, Rep.':'South Korea',
                           'Iran, Islamic Rep.':'Iran',
                       'Hong Kong SAR, China':'Hong Kong'})
    
    GDP[ (GDP['Country Name']=='Korea, Rep.')|
    (GDP['Country Name']=='Iran, Islamic Rep.')|
    (GDP['Country Name']=='Hong Kong SAR, China') ]['Country name']=temp3 
    
    
    ### 1.3 构建DataFrame: ScimEn
    ScimEn=pd.read_excel('scimagojr-3.xlsx')
    
    
    ### 1.4 连接以上三个DataFrame
    #将GDA的国家名改一下,方便拼接
    GDP.rename(columns={'Country Name':'Country'},inplace=True)  
    
    #三表拼接
    Final=pd.merge(pd.merge(ScimEn,Energy,on='Country',how='outer'),
               GDP,how='outer',on='Country')
    
    #将Country列设为索引列
    Final.set_index('Country',inplace=True)
    
    #筛除一部分不要的列
    temp4=list(Final.columns)[:10]+list(Final.columns)[-10:]
    Final=Final[temp4]
    
    #筛选Rank值为 1-15
    Final=Final[(Final.Rank>=1) & (Final.Rank<=15)]    

    return Final #按照题目要求返回DataFrame (### 1.5 构建函数,返回所需内容)

In [4]:
Final=quesion1()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [5]:
Final.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,NaN,NaN,NaN,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,NaN,NaN,NaN,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12

<font color = red size = 5>**以下所有问题都基于这个（15，20）的DataFrame** </font>

# 问题2 

过去2006-2015年每个国家的平均GDP是多少？（需跳过缺失的数据）
定义一个Funtion，Return一个名为`avgGDP`的pandas.Series类型，其中index是15个国家名，数据是这些国家的平均GDP，且按照平均GDP降序排列。

In [5]:
avg=Final.iloc[:,10:]

In [6]:
avg

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,
China,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [7]:
avg['avgGDP']=avg.mean(axis=1)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [8]:
avg

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,avgGDP
Country,,,,,,,,,,,
China,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,6.348609e+12
United States,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,1.536434e+13
Japan,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,5.542208e+12
United Kingdom,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,2.487907e+12
Russian Federation,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.565459e+12
Canada,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,1.660647e+12
Germany,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,3.493025e+12
India,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.769297e+12
France,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,2.681725e+12
South Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,2.120175e+12
Spain,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,1.418078e+12
Iran,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,1.164043e+12
Brazil,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.189794e+12

In [9]:
avg.sort_values(by='avgGDP',ascending=False).iloc[:,-1]

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea                    NaN
Iran                           NaN
Name: avgGDP, dtype: float64

In [10]:
def question2():
    #提取出十年的GDP数据
    avg=Final.iloc[:,10:]  
    
    #计算每个国家2006-2015年的平均GDP
    avg['avgGDP']=avg.mean(axis=1)    
    
    #按平均GDP降序排序并取出平均GDP值
    avgGDP=avg.sort_values(by='avgGDP',ascending=False).iloc[:,-1]  
    
    return avgGDP

In [11]:
avgGDP=question2()
avgGDP

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea                    NaN
Iran                           NaN
Name: avgGDP, dtype: float64

# 问题3
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

在过去的10年里，这个平均GDP排名第六的国家的GDP发生了多大的变化




过去10年内，GDP变化的最大值是多少？（变化最大的衡量标准：2015年GPD减去2006年GDP，差值最大）

定义一个Funtion，返回这个数值。

In [12]:
list(avgGDP.index)[5]

'United Kingdom'

In [14]:
avg.loc['United Kingdom']

2006      2.419631e+12
2007      2.482203e+12
2008      2.470614e+12
2009      2.367048e+12
2010      2.403504e+12
2011      2.450911e+12
2012      2.479809e+12
2013      2.533370e+12
2014      2.605643e+12
2015      2.666333e+12
avgGDP    2.487907e+12
Name: United Kingdom, dtype: float64

In [16]:
avg.loc['United Kingdom'][-2]-avg.loc['United Kingdom'][0]

246702696075.3999

In [17]:
avg['2015']-avg['2006']

Country
China                 4.805667e+12
United States         1.756269e+12
Japan                 1.730216e+11
United Kingdom        2.467027e+11
Russian Federation    2.303563e+11
Canada                2.281399e+11
Germany               3.526652e+11
India                 1.101312e+12
France                1.533457e+11
South Korea                    NaN
Italy                -1.528541e+11
Spain                 4.998675e+09
Iran                           NaN
Australia             2.793118e+11
Brazil                4.743437e+11
dtype: float64

In [18]:
max(avg['2015']-avg['2006'])

4805667477850.389

In [21]:
def question3():
    #获取平均GDP排名第六的国家名
    temp=list(avgGDP.index)[5] 
    
    #计算过去十年这个国家GDP发生的变化大小
    var_mean=avg.loc['United Kingdom'][-2]-avg.loc['United Kingdom'][0]
    
    #计算过去十年,GDP变化的最大值
    var_max=max(avg['2015']-avg['2006'])    
    
    return var_mean,var_max

In [22]:
var_mean,var_max=question3()
print('过去十年平均GDP排名第六的国家GDP发生的变化:',var_mean)
print('过去十年,GDP变化的最大值:',var_max)

过去十年平均GDP排名第六的国家GDP发生的变化: 246702696075.3999
过去十年,GDP变化的最大值: 4805667477850.389

# 问题4

求Energy Supply per Capita的mean值。

定义一个Funtion，返回这个数值。

In [25]:
Final.head(1)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.7,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12

In [27]:
Final['Energy Supply per capita']

Country
China                  93.0
United States           NaN
Japan                 149.0
United Kingdom          NaN
Russian Federation    214.0
Canada                296.0
Germany               165.0
India                  26.0
France                166.0
South Korea             NaN
Italy                 109.0
Spain                 106.0
Iran                    NaN
Australia             231.0
Brazil                 59.0
Name: Energy Supply per capita, dtype: float64

In [28]:
Final['Energy Supply per capita'].mean()

146.72727272727272

In [32]:
def question4():
    Energy_mean=Final['Energy Supply per capita'].mean()    
    return Energy_mean

# 问题5

哪个国家的'% Renewable'最大？

定义一个Funtion，返回一个tuple，包含这个国家的国家名和对应的'% Renewable'数值。

In [42]:
Final['%Renewable']

Country
China                 19.75491
United States              NaN
Japan                 10.23282
United Kingdom             NaN
Russian Federation    17.28868
Canada                61.94543
Germany               17.90153
India                 14.96908
France                17.02028
South Korea                NaN
Italy                 33.66723
Spain                 37.96859
Iran                       NaN
Australia             11.81081
Brazil                69.64803
Name: %Renewable, dtype: float64

In [40]:
Final['%Renewable'].max()

69.64803

In [41]:
Final['%Renewable'].argmax()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """Entry point for launching an IPython kernel.

'Brazil'

In [43]:
def quesiont5():
    #获取最大 %Renewable 值的国家名
    name=Final['%Renewable'].argmax()    
    
    #获取最大 %Renewable 值
    R_max=Final['%Renewable'].max()    
    
    #讲结果组成元组输出
    result=(name,R_max)
    
    return result

In [45]:
quesiont5()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  This is separate from the ipykernel package so we can avoid doing imports until

('Brazil', 69.64803)

# 问题6


在原有的Dataframe上增加一列，计算 Self-Citations除以Total Citations的比例，并且命名这一列名为“Ratio of citation”。
这个比例的最大值是多少？对应的是哪个国家？
定义一个Funtion，返回一个tuple，包含这个国家的国家名和对应的ratio值。

In [48]:
Final['Citations'].sum()

3026654.0

In [49]:
Final['Ratio of citation']=Final['Self-citations']/Final['Citations'].sum()

In [50]:
Final.head(1)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,Ratio of citation
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.7,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.136019

In [51]:
def question6():
    #计算 Ratio of citation
    Final['Ratio of citation']=Final['Self-citations']/Final['Citations'].sum() 
    
    #获取最大 %Renewable 值的国家名
    name=Final['Ratio of citation'].argmax()    
    
    #获取最大 %Renewable 值
    R_max=Final['Ratio of citation'].max()    
    
    #讲结果组成元组输出
    result=(name,R_max)
    
    return result

In [52]:
question6()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: FutureWarning:
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """

('China', 0.1360191815780727)

# 问题 7

在原有的Dataframe上增加一列，使用 Energy Supply 除以 Energy Supply per capita 估算population。
人口数第三大的国家是谁？
定义一个Funtion，返回这个国家的名称。

In [7]:
Final.head(1)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.7,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12

In [8]:
Final['population']=Final['Energy Supply']/Final['Energy Supply per capita']

In [13]:
Final.sort_values('population',ascending=False).head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,population
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.059153e+08
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.435000e+08
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.274094e+08

In [15]:
list(Final.index)

['China',
 'United States',
 'Japan',
 'United Kingdom',
 'Russian Federation',
 'Canada',
 'Germany',
 'India',
 'France',
 'South Korea',
 'Italy',
 'Spain',
 'Iran',
 'Australia',
 'Brazil']

In [16]:
def question7():
    #计算population列
    Final['population']=Final['Energy Supply']/Final['Energy Supply per capita']  
    
    #取出population第三大的国家
    Final.sort_values('population',ascending=False,inplace=True)
    third_max=list(Final.index)[2]
    
    return third_max

In [17]:
question7()

'Brazil'

# 问题8

在原有的Dataframe上增加一列，估算单人的citable documents。提示：使用上一题估算出了人口数和citable documents总数计算出。

单人citable documents和energy supply per capita的correlation是多少，请使用`.corr()`, 使用Pearson算法。

定义一个funtion，返回这个数值。

In [18]:
Final.head(2)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,population
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09

In [19]:
Final['citable documents per population']=Final['Citable documents']/Final['population']

In [20]:
Final.head(2)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,population,citable documents per population
Country,,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09,0.000093
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09,0.000012

In [21]:
Final[['Energy Supply per capita','citable documents per population']].corr(method='pearson')

,Energy Supply per capita,citable documents per population
Energy Supply per capita,1.000000,0.875162
citable documents per population,0.875162,1.000000

In [22]:
Final[['Energy Supply per capita','citable documents per population']].corr(method='pearson').iloc[0,1]

0.8751624173721784

In [23]:
def question8():
    #计算单人的citable documents
    Final['citable documents per population']=Final['Citable documents']/Final['population']  
    
    #计算Energy Supply per capita 和 citable documents per population的相关系数矩阵
    temp=Final[['Energy Supply per capita','citable documents per population']].corr(method='pearson')
    
    return temp.iloc[0,1]

In [24]:
question8()

0.8751624173721784

# 问题9


创建一列名为“HighRenew”，将% Renewable值大于等于所有国家% Renewable的median值的，标记为1；小于所有国家% Renewable的median值的，标记为0。定义一个funtion，返回一个pandas.Series，index为国家名，排序为Rank升序。

In [35]:
Final.head(1)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,population,citable documents per population
Country,,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.7,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09,0.000093

In [40]:
def temp(x):
    if x>=Final['%Renewable'].median():
        temp=1
    else:
        temp=0
    return temp

In [41]:
Final['%Renewable'].map(temp)

Country
China                 1
India                 0
Brazil                1
Russian Federation    0
Japan                 0
Germany               1
France                0
Italy                 1
Spain                 1
Canada                1
Australia             0
United States         0
United Kingdom        0
South Korea           0
Iran                  0
Name: %Renewable, dtype: int64

In [42]:
print(Final['%Renewable'].median())
Final['%Renewable']

17.90153

Country
China                 19.75491
India                 14.96908
Brazil                69.64803
Russian Federation    17.28868
Japan                 10.23282
Germany               17.90153
France                17.02028
Italy                 33.66723
Spain                 37.96859
Canada                61.94543
Australia             11.81081
United States              NaN
United Kingdom             NaN
South Korea                NaN
Iran                       NaN
Name: %Renewable, dtype: float64

In [43]:
Final['HighRenew']=Final['%Renewable'].map(temp)

In [46]:
Final.sort_values(by='Rank')['HighRenew']

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    0
Canada                1
Germany               1
India                 0
France                0
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

In [48]:
def question9():
    #定义编码函数
    def temp(x):
        if x>=Final['%Renewable'].median():
            temp=1
        else:
            temp=0
        return temp
    
    #计算 HighRenew列
    Final['HighRenew']=Final['%Renewable'].map(temp)   
    
    #按Rank升序排序,取出 HighRenew 列
    temp1=Final.sort_values(by='Rank')['HighRenew']   
    
    return temp1

In [49]:
question9()

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    0
Canada                1
Germany               1
India                 0
France                0
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

# 问题 10

使用以下dict将国家与大洲（Continent）名称匹配。创建一个新的DataFrame，显示每个大洲的数据样本的size，人口数量的总和，mean值，和标准差。提示：人口数量根据前面题目来预估计算。

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

定义一个Funtion，返回一个DataFrame，index为大洲名`['Asia', 'Australia', 'Europe', 'North America', 'South America']`；列名为`['size', 'sum', 'mean', 'std']`

In [51]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

In [56]:
Final.index.map(ContinentDict)

Index(['Asia', 'Asia', 'South America', 'Europe', 'Asia', 'Europe', 'Europe',
       'Europe', 'Europe', 'North America', 'Australia', 'North America',
       'Europe', 'Asia', 'Asia'],
      dtype='object', name='Country')

In [57]:
Final.index=Final.index.map(ContinentDict)
Final.head()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,population,citable documents per population,HighRenew
Country,,,,,,,,,,,,,,,,,,,,,,,
Asia,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09,0.000093,1
Asia,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09,0.000012,0
South America,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.059153e+08,0.000042,1
Europe,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.435000e+08,0.000128,0
Asia,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.274094e+08,0.000238,0

In [65]:
Continent1=Final['Rank'].groupby(by='Country').count()
Continent1

Country
Asia             5
Australia        1
Europe           6
North America    2
South America    1
Name: Rank, dtype: int64

In [69]:
Continent=Final['population'].groupby(by='Country').agg(['sum','mean','std'])

In [70]:
Continent['size']=Continent1

In [76]:
Continent.index.name='Continent'

In [78]:
Continent=Continent[['size','sum','mean','std']]
Continent

               size           sum          mean           std
Continent
Asia              5  2.771785e+09  9.239284e+08  6.913019e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  3.940587e+08  7.881174e+07  3.813228e+07
North America     2  3.523986e+07  3.523986e+07           NaN
South America     1  2.059153e+08  2.059153e+08           NaN

In [20]:
def question10():
    #定义大洲替换字典
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    
    #替换索引及索引名称为大洲
    Final.index=Final.index.map(ContinentDict)
    Final.index.name='Continent'
    
    #计算每个大洲的样本数据size
    size_temp=Final['Rank'].groupby(by='Country').count()
    
    #计算population的统计指标
    Continent=Final['population'].groupby(by='Country').agg(['sum','mean','std']) 
    
    #将size数据添加到dataframe Continent中
    Continent['size']=size_temp    
    
    #调整一下列的位置
    Continent=Continent[['size','sum','mean','std']]
    
    return Continent

# 问题 11

将`% Renewable`cut为5个bins，然后goupby大洲名称和这5个bins。提示：index为multiindex.

以上每个group中有多少个国家？定义一个function，返回一个Series，mutiindex为'Continent', bins for '% Renewable'。

In [81]:
Final.index.name='Continent'

In [84]:
Final['bins for % Renewable']=pd.cut(Final['%Renewable'],5)

In [88]:
result=Final.groupby(by=['Continent','bins for % Renewable']).count()['Rank']
result

Continent      bins for % Renewable
Asia           (10.173, 22.116]        3.0
               (22.116, 33.999]        NaN
               (33.999, 45.882]        NaN
               (45.882, 57.765]        NaN
               (57.765, 69.648]        NaN
Australia      (10.173, 22.116]        1.0
               (22.116, 33.999]        NaN
               (33.999, 45.882]        NaN
               (45.882, 57.765]        NaN
               (57.765, 69.648]        NaN
Europe         (10.173, 22.116]        3.0
               (22.116, 33.999]        1.0
               (33.999, 45.882]        1.0
               (45.882, 57.765]        NaN
               (57.765, 69.648]        NaN
North America  (10.173, 22.116]        NaN
               (22.116, 33.999]        NaN
               (33.999, 45.882]        NaN
               (45.882, 57.765]        NaN
               (57.765, 69.648]        1.0
South America  (10.173, 22.116]        NaN
               (22.116, 33.999]        NaN
               (33.999, 45.882]        NaN
               (45.882, 57.765]        NaN
               (57.765, 69.648]        1.0
Name: Rank, dtype: float64

In [90]:
result.fillna(0,inplace=True)

In [94]:
result.rename(index='Continent',inplace=True)

Continent      bins for % Renewable
Asia           (10.173, 22.116]        3.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        0.0
Australia      (10.173, 22.116]        1.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        0.0
Europe         (10.173, 22.116]        3.0
               (22.116, 33.999]        1.0
               (33.999, 45.882]        1.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        0.0
North America  (10.173, 22.116]        0.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        1.0
South America  (10.173, 22.116]        0.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        1.0
Name: Continent, dtype: float64

In [109]:
def question11():
    #修改索引名称
    Final.index.name='Continent'    
    
    #分箱
    Final['bins for % Renewable']=pd.cut(Final['%Renewable'],5)   
    
    #分组计数
    result=Final.groupby(by=['Continent','bins for % Renewable']).count()['Rank']
    
    #将nan填充为0
    result.fillna(0,inplace=True)    
    
    #修改Series的名称
    result.rename(index='Continent',inplace=True)
    
    return result

In [110]:
question11()

Continent      bins for % Renewable
Asia           (10.173, 22.116]        3.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        0.0
Australia      (10.173, 22.116]        1.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        0.0
Europe         (10.173, 22.116]        3.0
               (22.116, 33.999]        1.0
               (33.999, 45.882]        1.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        0.0
North America  (10.173, 22.116]        0.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        1.0
South America  (10.173, 22.116]        0.0
               (22.116, 33.999]        0.0
               (33.999, 45.882]        0.0
               (45.882, 57.765]        0.0
               (57.765, 69.648]        1.0
Name: Continent, dtype: float64

# 问题12


将人口数的数值转化为这样：317615384.61538464 -> 317,615,384.61538464。

定义一个function，返回一个Series，名称为'PopEst'，index为国家名，值为转化好的population（string类型）

In [166]:
Final=quesion1()
question7()
Final.head()

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per capita,%Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,population
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.75491,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.367645e+09
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.96908,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.276731e+09
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.64803,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.059153e+08
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.28868,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.435000e+08
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.23282,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.274094e+08

In [160]:
def temp1(x):
    #设置空列表.用于接收待插入位置后的索引值
    temp=[]
    
    #将输入的数值转化为字符串
    sample=str(x)
    
    #定位小数点的位置索引
    dot=sample.find('.')
    
    #设置待插入位置的初始值
    dot=dot-3
    
    #用循环将所有符合的待插入位置索引值找到
    while dot>0:
        temp.append(dot)
        dot=dot-3
        
    #将输入值转化后的字符串转化为列表    
    t=list(sample)
    
    #依次在各个待插入位置插入逗号
    for i in temp:
        t.insert(i,',')
    
    #将插入完成的结果列表转化为字符串
    s=''.join(t)   
    
    return s

In [167]:
temp1(Final['population'][0])

'1,367,645,161.2903225'

In [168]:
temp1(317615384.61538464)

'317,615,384.61538464'

In [169]:
Final['population'][0]

1367645161.2903225

In [170]:
str(Final['population'][0]).find('.')

10

In [171]:
Final['PopEst']=Final['population'].map(temp1)

In [172]:
Final['PopEst']

Country
China                 1,367,645,161.2903225
India                 1,276,730,769.2307692
Brazil                 205,915,254.23728815
Russian Federation            143,500,000.0
Japan                  127,409,395.97315437
Germany                 80,369,696.96969697
France                  63,837,349.39759036
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Canada                  35,239,864.86486486
Australia              23,316,017.316017315
United States                           nan
United Kingdom                          nan
South Korea                             nan
Iran                                    nan
Name: PopEst, dtype: object

In [173]:
def question12():
    
    #编写转换函数
    def temp1(x):
        #设置空列表.用于接收待插入位置后的索引值
        temp=[]
    
        #将输入的数值转化为字符串
        sample=str(x)
    
        #定位小数点的位置索引
        dot=sample.find('.')
    
        #设置待插入位置的初始值
        dot=dot-3
    
        #用循环将所有符合的待插入位置索引值找到
        while dot>0:
            temp.append(dot)
            dot=dot-3
        
        #将输入值转化后的字符串转化为列表    
        t=list(sample)
    
        #依次在各个待插入位置插入逗号
        for i in temp:
            t.insert(i,',')
    
        #将插入完成的结果列表转化为字符串
        s=''.join(t)   
    
        return s   

    #转换 population类型并生成新列 'PopEst'
    Final['PopEst']=Final['population'].map(temp1)

    return   Final['PopEst']

In [174]:
question12()

Country
China                 1,367,645,161.2903225
India                 1,276,730,769.2307692
Brazil                 205,915,254.23728815
Russian Federation            143,500,000.0
Japan                  127,409,395.97315437
Germany                 80,369,696.96969697
France                  63,837,349.39759036
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Canada                  35,239,864.86486486
Australia              23,316,017.316017315
United States                           nan
United Kingdom                          nan
South Korea                             nan
Iran                                    nan
Name: PopEst, dtype: object